version: "3.2"
services:
  #mysql:
  #  image: mysql:5.7.26
  #  ports:
  #    - "3306:3306"
  #  container_name: mysql
  #  environment:
  #    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  #    - MYSQL_DATABASE=testdb
  #    - MYSQL_USER=testuser
  #    - MYSQL_PASSWORD=testpass
  #    - TZ=Asia/Tokyo
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
      TZ: Asia/Tokyo
    ports:
      - '5432:5432'